
version: "3.3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 220.100.30.0/24

services:
  setup:
    container_name: setup
    #extends:
    #  file: peer-base.yaml
    #  service: ca-env
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - ORDERER_HOME=/etc/hyperledger/orderer
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/mkMsp.sh; sleep 99999'
    volumes:
      - ../scripts/common:/scripts
      - ../crypto-config:/crypto-config
      - ../channel-artifacts:/root/data
      - ../organizations:/organizations
      - ../bin:/extra_bin
    networks:
      - network
    depends_on: 
      - ca.peer.google.com
      - ca.peer.naver.com
      - ca.orderer.google.com

  ca.peer.google.com:
    container_name : ca.peer.google.com
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.peer.google.com
      #- FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7060
      - FABRIC_CA_SERVER_CSR_CN=finger
    ports:
      - 7060:7060
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../data/ca/fabric-ca/ca.peer.google.com:/etc/hyperledger/fabric-ca-server
    networks:
      - network
  

  ca.peer.naver.com:
    container_name : ca.peer.naver.com
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.peer.naver.com
      #- FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7061
      - FABRIC_CA_SERVER_CSR_CN=finger
    ports:
      - 7061:7061
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../data/ca/fabric-ca/ca.peer.naver.com:/etc/hyperledger/fabric-ca-server
    networks:
      - network
  

  ca.orderer.google.com:
    container_name: ca.orderer.google.com
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.orderer.google.com
      #- FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8060
    ports:
      - 8060:8060
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../data/ca/fabric-ca/ca.orderer.google.com:/etc/hyperledger/fabric-ca-server
    networks:
      - network 
  
