version: "3.3"

networks:
  test-network:
    ipam:
      driver: default
      config:
        - subnet: "220.100.30.0/24"


services:

  #CA_PEER_SERVER:
  peer.google.com:
    container_name : $CA_PEER_ORG_NAME.$SD.$DOMAIN
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=$CA_PEER_ORG_NAME.$SD.$DOMAIN
      #- FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../data/ca/fabric-ca/ca.google.com:/etc/hyperledger/fabric-ca-server
    networks:
      - test-network

 # CA_ORD_SERVER:
  orderer.google.com:
    container_name: $CA_ORD_ORG_NAME.$SD.$DOMAIN
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=$CA_ORD_ORG_NAME.$SD.$DOMAIN
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - 8054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../data/ca/fabric-ca/ca.orderer.google.com:/etc/hyperledger/fabric-ca-server
    networks:
      - test-network

  orderer1.google.com:
    container_name: peer1.google.com
    image: hyperledger/fabric-orderer:2.3.0
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTEADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTRENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      # - ORDERER_KAFKA_TOPIC_REPLCATIONFACTOR=1
      # - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/ordewrer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderqer/orderer.genesis.block
        - ../organizations/ordererOrganizations/google.com/orderers/orderer.google.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/google.com/orderters/orderer.google.com/tls/:/var/hyperledger/orderer/tls
        - ../data/blockchain/orderer1.google.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - test-network

  peer1.google.com:
    container_name: peer1.google.com
    image: hyperledger/fabric-peer:2.3.0
    #image: hyperledger/fabric-peer:${IMAGE_TAG}
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$(COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENANBLE=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.google.com
      - CORE_PEER_ADDRESS=peer1.google.com:8050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8050
      - CORE_PEER_CHAINCODEADDRESS=peer1.google.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.google.com:8050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.google.com:8050
      - CORE_PEER_LOCALMSPID=CkgMSP
      # couchdb
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.google.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizatoins/google.com/peers/peer1.google.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/google.com/peers/peer1.google.com/tls:/etc/hyperledger/fabric/tls
      - ../data/blockchain/peer1.google.com/:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - couchdb1.google.com
    ports:
      - 8050:8050
    networks:
      - test-network

  couchdb1.google.com:
    container_name: couchdb1.google.com
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - test-network
